// examples/vue-demo/src/example3/index.vue
<template>
  <dnd-provider>
    <ul className="example3">
      <list-item 
        v-for="(item, index) in list"
        :key="item"
        :item="item"
        :index="index" 
        @onDragEnd="onDragEnd"
      />
    </ul>
  </dnd-provider>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { DndProvider } from 'easy-dnd/vue'
import ListItem from './ListItem.vue'

const list = ref([ 'a', 'b', 'c', 'd', 'e', 'f' ])

const onDragEnd = (fromIndex: number, toIndex: number, isTop: boolean) => {
  // 有两种情况不需要调换位置
  // 向上拖拽，并且toIndex就在fromIndex的上面
  if (isTop && fromIndex === toIndex - 1) return
  // 向下拖拽，并且toIndex就在fromIndex的下面
  if (!isTop && fromIndex === toIndex + 1) return

  const removeItem = list.value.splice(fromIndex, 1)
  list.value.splice(toIndex, 0, removeItem[0])
}
</script>

<style>
.example3 {
  margin: 100px;
  border: 1px solid #000;
}

.example3 > li {
  position   : relative;
  min-height : 30px;
  border     : 1px dashed #000;
  margin     : 0 10px;
  list-style : none;
  line-height: 30px;
}

.example3 > li::after,
.example3 > li::before {
  width   : 100%;
  height  : 10px;
  content : '';
  display : block;
  position: absolute;
}

</style>

// examples/react-demo/src/example3/index.tsx
import { useMemo, useState } from 'react'
import { DndProvider, useDrag, useDrop } from 'easy-dnd/react'
import './index.css'

function Example3() {
  return (
    <DndProvider>
      <List />
    </DndProvider>
  )
}

function List() {

  const [ list, setList ] = useState([ 'a', 'b', 'c', 'd', 'e', 'f' ])

  const onDragEnd: ItemProps['onDragEnd'] = (fromIndex, toIndex, isTop) => {
    // 有两种情况不需要调换位置
    // 向上拖拽，并且toIndex就在fromIndex的上面
    if (isTop && fromIndex === toIndex - 1) return
    // 向下拖拽，并且toIndex就在fromIndex的下面
    if (!isTop && fromIndex === toIndex + 1) return

    const newList = [ ...list ]
    const removeItem = newList.splice(fromIndex, 1)
    newList.splice(toIndex, 0, removeItem[0])
    setList(newList)

  }

  return (
    <ul className='example3'>
      {
        list.map((item, index) => (
          <Item
            key={item}
            index={index}
            value={item}
            onDragEnd={onDragEnd}
          />
        ))
      }
    </ul>
  )

}

interface ItemProps {
  value: string,
  index: number,
  onDragEnd: (fromIndex: number, toIndex: number, isTop: boolean) => void
}

function Item({ value, index, onDragEnd }: ItemProps) {

  const dragInstance = useDrag(() => ({
    config: {
      type:      'list',
      // 把索引作为存放数据
      data:      () => index,
      className: {
        dragging: 'dragging'
      }
    }
  }), [ index ])

  const dropInstance = useDrop<number>(() => ({
    config: {
      acceptType: new Set([ 'list' ])
    },
    // 进入时触发的函数
    dragOver(monitor) {
      // 拖动到前50%
      if (monitor.isOverTop()) {
        dropInstance.dropDom.className = 'example3-enter-top'
      }
      // 拖动到后50%
      else {
        dropInstance.dropDom.className = 'example3-enter-bottom'
      }
    },
    // 离开
    dragLeave() {
      // 拖动的控件离开此控件，还原样式
      dropInstance.dropDom.className = ''
    },
    // 松开
    drop(monitor) {
      const isTop = monitor.isOverTop()
      console.log(
        `${monitor.getDragData()}拖动到${index}的${isTop ? '上' : '下'}面`
      )
      // 修改数据
      onDragEnd(monitor.getDragData(), index, isTop)
      // @ts-ignore dragLeave一定用不到任何参数
      this.dragLeave && this.dragLeave()
    }
  }), [ index, onDragEnd ])

  // 当前控件既可以拖拽，也可以放置
  const dropDragRef = useMemo(() => dropInstance.dropRef(dragInstance.dragRef), [])

  return (
    <li ref={dropDragRef}>
      {index} {value}
    </li>
  )
}

Example3.tip = '拖拽排序'

export {
  Example3
}
